apiVersion: v1
kind: Service
metadata:
  name: netcortex-telemetry
  namespace: netcortex
  labels:
    app: netcortex-telemetry
    app.kubernetes.io/part-of: netcortex
spec:
  type: ClusterIP
  selector:
    app: netcortex-telemetry
  ports:
  - port: 9001
    targetPort: 9001
    protocol: TCP
    name: mcp
